### ISSUE TITLE
pip install fails on NVIDIA XAVIER

### ISSUE THREAD

**Issue by pdavis39** [usajusaj/segmentation#2]
ath.hpp:47:12: fatal error: x86intrin.h: No such file or directory
     #include <x86intrin.h>
              ^~~~~~~~~~~~~
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for segmentation

**Comment by usajusaj** [comment]
Hi @pdavis39, thanks for the report. 
I was able to recreate the problem on an rpi and am working on a solution.
M
